# config/validator/validation.yaml
App\Entity\Location:
  properties:
    Longitude:
      - Range:
          min: -180
          max: 180
          groups: [new, edit]
    latitude:
      - Range:
          min: -90
          max: 90
          groups: [new, edit]
App\Entity\Weather:
  properties:
    temperature:
      - Range:
          min: -50
          max: 60
          groups: [new, edit]
